# SonarQube configuration
sonar.projectKey=ach-ops_Projet_MIAGE_Genie_logiciel
sonar.organization=ach-ops

# Sources
sonar.sources=backend,frontend/src
sonar.tests=backend/tests

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  backend/data/**,\
  backend/tests/**,\
  **/*.min.js,\
  frontend/src/__tests__/**,\
  frontend/src/**/*.spec.ts,\
  frontend/src/**/*.test.ts

sonar.test.exclusions=\
  **/node_modules/**,\
  **/dist/**

sonar.coverage.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  backend/tests/**,\
  frontend/src/**,\
  backend/index.js

# Coverage
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

# Encodage
sonar.sourceEncoding=UTF-8
